### ISSUE TITLE
String.getOctave does not respect accidentals

### ISSUE THREAD

**Issue by aspiers** [supercollider-quarks/wslib#11]
As documented in https://github.com/supercollider-quarks/wslib/pull/10/files#diff-12e00ae2f727ba75e4f5ccf4da217f2fR82, `String.getOctave` does not respect accidentals, e.g.

    "Cb3".getOctave; // -> 3
    "B#4".getOctave; // -> 4

I would expect these to return `2` and `5` respectively.  Tests with this expectation have been submitted in #12.

**Comment by woutersnoei** [comment]
Hi, I'm not sure if that would be correct behavior. As I learned it the C (with or without accidental) is where the next octave starts. Even if a Cb3 enharmonically sounds the same as a B2, it is technically a different note. Also, the number it returns is simply the octave number specified in the string, no calculation is done there..
