### ISSUE TITLE
I get an error from class "DOMElement" 

### ISSUE THREAD

**Issue by thedurf18** [supercollider-quarks/wslib#14]
I tried adding the quark to my extensions folder in SuperCollider, but I get this error message:
"ERROR: Class extension for nonexistent class 'DOMElement'
     In file:'/Users/daniel/Library/Application Support/SuperCollider/Extensions/wslib-master/wslib-classes/Main Features/SVGFile/extVarious-SVGFile.sc' "

Not sure how to fix this issue.

**Comment by dyfer** [comment]
I believe DOMElement is part of the XML quark, installing it should fix it.
