### ISSUE TITLE
unneeded SCClassLibrary Common 3.7 method overwrites

### ISSUE THREAD

**Issue by redFrik** [supercollider-quarks/wslib#2]
all these methods are now implemented in common sc (at least in sc3.7)
Dictionary:++
Env:ar
Env:duration
Env:kr
SimpleNumber:madd
UGen:blend
UGen:isUGen

would be nice if they were (eventually) removed from this quark.

**Comment by woutersnoei** [comment]
I think these were all removed (a while ago now) so this issue can close, thanks!
